stages:
  - build
  - deploy 

before_script:
  - apt-get install -y software-properties-common; add-apt-repository ppa:deadsnakes/ppa; apt-get -qq update; apt-get -y -qq install python3.6
  - apt-get update -qq && apt-get install -y -qq python3-pip jq
  - pip3 install awscli virtualenv
  
build:
  stage: build
  script:
    - ./bin/build.sh

deploy:
  stage: deploy
  script:
    - ./bin/deploy.sh

  